# Install Nginx by ppk

---
# ----------------------
# Install Nginx on CentOS
# ----------------------
- tags: nginx
  become: yes
  when: system_os is defined and system_os == 'centos'
  block:
    - name: Update nginx repo on centos
      copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo mode=0644

    - name: Update repo list
      shell: {{ item }}
      with_items:
        - yum clean all
        - yum update -y

    - name: Install nginx on centos
      yum: name=nginx state=latest update_cache=yes

    - name: Set nginx run level on centos
      shell: chkconfig --level 345 nginx on

# ----------------------
# Install Nginx on Ubuntu
# ----------------------
- tags: nginx
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  block:
    - name: Update nginx repo on ubuntu
      shell: deb http://nginx.org/packages/ubuntu/ lucid nginx; \
             deb-src http://nginx.org/packages/ubuntu/ lucid nginx

    - name: Install nginx on ubuntu
      apt: name=nginx state=latest update_cache=yes

# ----------------------
# Start Nginx
# ----------------------
- name: Start nginx
  become: True
  tags: nginx
  service: name=nginx state=started