---
- name: Setup docker hosts
  # hosts: chexiang:&docker
  # hosts: docker01,docker02
  # hosts: all
  hosts: regis2,builder2,ds
  # hosts: ds1
  user: devops
  vars:
    user: devops
    home: /home/devops
  roles:
    - dns
    # - repo
    - foundation
    # - node
    # - git
    # - python
    # - supervisor
    # - docker
    # - docker-worker
