---

- name: test
  hosts: localhost
  vars:
    message: >
      aaa
      bbb
      ccc
    new_message: "{{ message[0:-1] }}"
  tasks:
    - debug:
        msg: "{{message}}"
        var: new_message

