---
- name: Install python packages
  tags: python
  # sometimes origin pip is faster than mirror
  # pip: name={{item}} extra_args='--trusted-host pypi.mirrors.ustc.edu.cn -i http://pypi.mirrors.ustc.edu.cn/simple'
  # pip: name={{item}}
  shell: "{{pip27}} install --upgrade {{douban_pypi}} {{item}}"
  with_items:
    - virtualenv
    - uwsgi

- name: Replace pyenv shims pyenv
  tags: python
  become: True
  shell: "ln -sf {{pyenv}}/versions/3.8.8/bin/{{item}} {{pyenv}}/shims/."
  with_items:
    - virtualenv
    - uwsgi

- name: Replace /usr/local/bin/pyenv
  tags: python
  become: True
  shell: "ln -sf {{pyenv}}/versions/3.8.8/bin/{{item}} /usr/local/bin/."
  with_items:
    - virtualenv
    - uwsgi
