---
- name: Install python packages
  tags: python
  pip: name={{item}} extra_args='--trusted-host pypi.douban.com -i http://pypi.douban.com/simple'
  with_items:
    - virtualenv
    - uwsgi

- name: Replace pyenv shims pyenv
  tags: python
  become: True
  shell: "ln -sf {{home}}/.pyenv/versions/2.7.10/bin/{{item}} {{home}}/.pyenv/shims/."
  with_items:
    - virtualenv
    - uwsgi

- name: Replace /usr/local/bin/pyenv
  tags: python
  become: True
  shell: "ln -sf {{home}}/.pyenv/versions/2.7.10/bin/{{item}} /usr/local/bin/."
  with_items:
    - virtualenv
    - uwsgi
