---
- name: Is pyenv exists.
  tags:
    - python
    - pyenv
  shell: pyenv --version | echo ''
  register: is_pyenv_installed

- name: Clone pyenv repository.
  tags:
    - python
    - pyenv
  git: repo=https://github.com/yyuu/pyenv.git
       dest={{home}}/.pyenv
       depth=1
  when: is_pyenv_installed.stdout == ''

- name: Ensure fragments bash dir exits.
  tags:
    - python
    - pyenv
  file: dest={{home}}/.bash.d/ state=directory

- name: Install pyenv bash file.
  tags:
    - python
    - pyenv
  template: src=pyenv.bash dest={{home}}/.bash.d/pyenv.bash mode=0774 force=yes

- name: Make sure pyenv not existed in bashrc.
  tags:
    - python
    - pyenv
  shell: cat {{home}}/.bashrc | grep pyenv || echo ''
  register: is_pyenv_existed
# - debug: var=is_pyenv_existed

- name: add pyenv to .bashrc.
  tags:
    - python
    - pyenv
  lineinfile:
    line: "source {{home}}/.bash.d/pyenv.bash"
    dest: "{{home}}/.bashrc"
  when: is_pyenv_existed.stdout == ''

- name: Make sure python 2.7.14 has been installed.
  tags:
    - python
    - pyenv
  shell: pyenv versions | grep 2.7.14 || echo ''
  register: is_27_installed

- name: Make sure python 3.6.5 has been installed.
  tags:
    - python
    - pyenv
  shell: pyenv versions | grep 3.6.5 || echo ''
  register: is_34_installed

- name: Install python 2.7.14.
  tags:
    - python
    - pyenv
  shell: pyenv install 2.7.14
  when: is_27_installed.stdout == ''

- name: Install python 3.6.5.
  tags:
    - python
    - pyenv
  shell: pyenv install 3.6.5
  when: is_34_installed.stdout == ''

# sometimes strange
# pyenv could install python without pip
# so you need to double check whether the pip has been installed successfully.
- name: Double check pip2
  tags:
    - python
    - pyenv
  shell: pyenv global 2.7.14; \
         pip --version | cut -c 1-3
  ignore_errors: yes
  register: is_pip2_installed

- name: Double check pip3
  tags:
    - python
    - pyenv
  shell: pyenv global 3.6.5; \
         pip --version | cut -c 1-3
  ignore_errors: yes
  register: is_pip3_installed

- name: Reinstall pip2
  tags:
    - python
    - pyenv
  shell: pyenv global 2.7.14; \
         easy_install pip
  when: is_pip2_installed.stdout != 'pip'

- name: Reinstall pip3
  tags:
    - python
    - pyenv
  shell: pyenv global 3.6.5; \
         easy_install pip
  when: is_pip3_installed.stdout != 'pip'

- name: Upgrade pip.
  tags:
    - python
    - pyenv
  shell: pyenv rehash; \
         pyenv global 3.6.5; \
         pip install --upgrade pip; \
         pyenv global 2.7.14; \
         pip install --upgrade pip
