# 安装 virtualenvwrapper
# 因为 uwsgi 只支持 virtualenvwrapper

---
- name: Install virtualenvwrapper.
  tags: python
  # sometimes origin pip is faster than mirror
  command: "{{pip27}} install virtualenvwrapper"
  # command: "{{pip27}} install virtualenvwrapper {{douban_pypi}}"

- name: Copy virtualenvwrapper bash file.
  tags: python
  template: src=virtualenvwrapper.bash
            dest={{home}}/.bash.d/virtualenvwrapper.bash
            mode=0774
            force=yes

- name: Make sure virtualenvwrapper existed in bashrc.
  tags: python
  shell: "cat {{home}}/.bashrc | grep virtualenvwrapper || echo ''"
  register: is_virtualenvwrapper_existed

- name: add virtualenvwrapper to .bashrc.
  tags: python
  lineinfile:
    dest: "{{home}}/.bashrc"
    line: "source {{home}}/.bash.d/virtualenvwrapper.bash"
  when: is_virtualenvwrapper_existed.stdout == ''
