# 安装 virtualenvwrapper
# 因为 uwsgi 只支持 virtualenvwrapper

---
- name: Install virtualenvwrapper.
  tags: python
  # sometimes origin pip is faster than mirror
  command: "{{pip27}} install virtualenvwrapper"
  # command: "{{pip27}} install virtualenvwrapper {{douban_pypi}}"

- name: Copy virtualenvwrapper bash file.
  tags: python
  template: src=virtualenvwrapper.sh
            dest={{home}}/.bash.d/virtualenvwrapper.sh
            mode=0774
            force=yes

- name: Make sure virtualenvwrapper existed in bashrc.
  tags: python
  shell: "cat {{home}}/.bashrc | grep virtualenvwrapper || echo ''"
  register: is_virtualenvwrapper_existed

- name: Source .bashrc.
  tags: python
  shell: "source {{home}}/.bashrc"
