# Install latest Git on CentOS
# No testing!
---
- name: Install dependence
  tags: git
  become: yes
  yum: "name={{item}} state=latest update_cache=yes"
  when: system_os is defined and system_os == 'centos'
  with_items:
    - apr-devel
    - apr-util-devel
    - neon-devel
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel
    - gcc
    - perl-ExtUtils-MakeMaker

- name: Get current git version
  tags: git
  shell: git --version | cut -c 13-15 || echo '1'
  register: git_version

- tags: git
  become: yes
  block:
    - name: Remove old git
      yum: name=git state=removed

    - name: Copy git 2.7
      copy: src=git-2.7.0.tar dest="{{home}}/src/git-2.7.0.tar.gz"
      # get_url: url=https://www.kernel.org/pub/software/scm/git/git-2.7.0.tar.gz
      #          dest="{{home}}/src/git-2.7.0.tar.gz"

    - name: Unpack git tar
      unarchive: "src={{home}}/src/git-2.7.0.tar.gz dest={{home}}/src/ copy=no"

    - name: make
      shell: "{{item}}"
      with_items:
        - make prefix=/usr/local/git all
        - make prefix=/usr/local/git install
        - echo "export PATH=$PATH:/usr/local/git/bin" >> /etc/bashrc
      args:
        chdir: "{{home}}/src/git-2.7.0"
  when: system_os is defined and system_os == 'centos' and git_version.stdout|float < 2.7

