# Install latest Git on CentOS
# No testing!
---
- name: Remove old git
  tags: git
  become: True
  yum: name=git state=absent
  when: system_os is defined and system_os == 'centos'

- name: Install dependence
  tags: git
  become: True
  yum: "name={{item}} state=latest update_cache=yes"
  when: system_os is defined and system_os == 'centos'
  with_items:
    - apr-devel
    - apr-util-devel
    - neon-devel
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel

- name: Download git 2.5
  tags: git
  when: system_os is defined and system_os == 'centos'
  get_url: url=https://www.kernel.org/pub/software/scm/git/git-2.5.0.tar.gz
           dest=~/src/git-2.5.0.tar.gz

- name: Unpack git tar
  tags: git
  when: system_os is defined and system_os == 'centos'
  unarchive: "src={{home}}/src/git-2.5.0.tar.gz dest={{home}}/src/git-2.5.0 copy=no"

- name: make
  tags: git
  when: system_os is defined and system_os == 'centos'
  shell: "{{item}}"
  with_items:
    - make prefix=/usr/local/git all
    - make prefix=/usr/local/git install
    - echo "export PATH=$PATH:/usr/local/git/bin" >> /etc/bashrc
  become: True
  args:
    chdir: "{{home}}/src/git-2.5.0"
