# Install latest Git on Ubuntu
# No testing!

---
- tags: git
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  block:
    - name: App PPA
      apt_repository: repo='ppa:git-core/ppa'

    - name: Install git
      apt: name=git state=latest
