---
# CentOS
- become: yes
  tags:
    - foundation
    - ntp
  when: system_os is defined and system_os == 'centos'
  block:
    - name: Install ntp
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - ntp
        - ntpdate

    - name: enable ntp
      shell: chkconfig ntpd on


# Ubuntu
- become: yes
  tags:
    - foundation
    - ntp
  when: system_os is defined and system_os == 'ubuntu'
  block:
    - name: Install ntp
      apt:
        state: present
        update_cache: yes
        pkg:
          - ntp
          - ntpdate

# Service
- become: yes
  tags:
    - foundation
    - ntp
    - timezone
  block:
    - name: set timezone
      ignore_errors: yes
      shell: timedatectl set-timezone UTC

    - name: restart ntpd
      ansible.builtin.systemd:
        name: ntp
        state: restarted
        daemon_reload: yes
