---
# Centos
- become: yes
  tags:
    - packages
    - foundation
  when: system_os is defined and system_os == 'centos'
  block:
    - name: Install epel-release
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release

    - name: remove rpmforge
      shell: yum remove -y rpmforge-release

    - name: Upgrade yum
      yum: name=* state=present update_cache=yes

    - name: Install environ on CentOS
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - autoconf
        - automake
        - make
        - gcc
        - gcc-c++
        - blas-devel
        - bzip2
        - bzip2-devel
        - ccache
        - cpio
        - curl-devel
        - expat-devel
        - gawk
        - gettext-devel
        - gtk2-devel
        - lapack-devel
        - lbzip2
        - libcurl
        - libffi
        - libffi-devel
        - libpcap
        - libpcap-devel
        - libselinux-python
        - libtool
        - libxml2
        - libxml2-devel
        - libxslt
        - libxslt-devel
        - libyaml
        - lzo-devel
        - mhash
        - mysql-devel
        - nasm
        - ncurses
        - ncurses-devel
        - openldap-devel
        - openssh
        - openssl-devel
        - patch
        - pcre-devel
        - perl
        - perl-Digest-SHA1
        - pkgconfig
        - readline-devel
        - ruby-devel
        - rubygems
        - sqlite
        - sqlite-devel
        - zlib-devel
        - yum-cron

    - name: Auto update yum
      service: name=yum-cron state=started enabled=yes


# Ubuntu
- tags:
    - packages
    - foundation
  become: yes
  when: system_os is defined and system_os == 'ubuntu'
  block:
    - name: Update apt cache
      shell: apt-get update

    - name: Install environ on Ubuntu
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - autoconf
        - automake
        - make
        - g++
        - gcc
        - build-essential
        - gfortran
        - libbz2-dev
        - libc6-dev
        - libffi-dev
        - liblapack-dev
        - libldap2-dev
        - libopenblas-dev
        - libsasl2-dev
        - libsqlite3-dev
        - libssl-dev
        - libtool
        - libxml2-dev
        - libxslt1-dev
        - ncurses-dev
        - openssl
        - python-dev
        - ruby-dev
        - zlib1g-dev

    - name: Upgrade apt
      apt: name=* state=present update_cache=yes
