---
- name: Install tools.
  become: True
  tags:
    - tools
    - foundation
  yum: name={{item}} state=latest update_cache=yes
  when: system_os is defined and system_os == 'centos'
  ignore_errors: yes
  with_items:
    - git
    - zsh
    - tmux
    - curl
    - htop
    - iftop
    - vim
    - wget
    - unzip
    - telnet
    - ruby-devel
    - pv
    - haveged
    - bash
    - libcap-ng-utils

- name: Install tools.
  become: True
  tags:
    - tools
    - foundation
  apt:
    pkg:
    - git
    - zsh
    - tmux
    - curl
    - htop
    - iftop
    - vim
    - wget
    - unzip
    - telnet
    - ruby-dev
    - pv
    - haveged
    - bash
    - libcap-ng-utils
    state: latest
    update_cache: yes
  when: system_os is defined and system_os == 'ubuntu'
  ignore_errors: yes

- name: Copy vimrc.
  tags:
    - tools
    - vimrc
    - foundation
  copy: src=vimrc dest=~/.vimrc mode=0664

- name: Copy bashrc.
  tags:
    - tools
    - bashrc
    - foundation
  copy: src=bashrc dest=~/.bashrc mode=0664

- name: Change user shell to bash
  become: True
  tags:
    - tools
    - bashrc
    - foundation
  user:
    name: "{{ item }}"
    state: present
    shell: /usr/bin/bash
  loop:
    - laisky

- name: Ensure fragments bash dir exits.
  tags:
    - tools
    - foundation
  file: dest=~/.bash.d/ state=directory mode=0755

- name: Install pyenv bash file.
  tags:
    - tools
    - foundation
  copy: src=git-complete.bash dest=~/.bash.d/git-complete.bash mode=0774
