# 在车享的机器里，需要删除这个废物

---
- name: Remove epel
  tags: repo
  become: yes
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /etc/yum.repos.d/epel.repo
    - /etc/yum.repos.d/epel-testing.repo
