---
- name: Remove old npm
  tags: node
  sudo: True
  apt: name={{item}} state=absent purge=true
  with_items:
    - nodejs
    - npm

- name: Update nodesource
  tags: node
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: Install node
  tags: node
  sudo: True
  apt: name=nodejs state=latest update_cache=yes

- name: Update npm
  tags: node
  sudo: True
  npm: name=npm global=yes

- name: Install basic package
  tags: node
  sudo: True
  npm: name={{item}} global=yes
  with_items:
    - less
    - gulp
    - bower
    - commitizen
    - conventional-changelog
