# Install docker-compose

---
- name: Download docker compose
  tags: docker
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.5.2/run.sh
    dest: /usr/bin/docker-compose
    mode: 755
    force: yes

- name: Initial docker-compose
  tags: docker
  become: yes
  shell: /usr/bin/docker-compose -v
