# Install docker-compose

---
- name: Install docker compose
  tags: docker
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m)"
    dest: /usr/local/bin/docker-composea
    mode: 0755

- name: Initial docker-compose
  tags: docker
  become: yes
  shell: /usr/local/bin/docker-compose -v
