# 安装 pipework
# 管理 Docker 的网络

---
- name: Clone pipework
  tags:
    - docker
    - pipework
  git:
    repo: https://github.com/jpetazzo/pipework.git
    dest: /tmp/pipework
    depth: 1

- name: Copy to /usr/bin
  tags:
    - docker
    - pipework
  become: yes
  file:
    src: /tmp/pipework/pipework
    path: /usr/bin/pipework
    state: link
    force: yes
    mode: 0755
