# 安装 pipework
# 管理 Docker 的网络

---
- name: Check pipework existed
  tags:
    - docker
    - pipework
  stat: path=/tmp/pipework
  register: pipest

- name: Remove pipework
  become: yes
  tags:
    - docker
    - pipework
  file:
    path: /tmp/pipework
    state: absent
  when: pipest.stat.exists

- name: Clone pipework
  tags:
    - docker
    - pipework
  git:
    repo: https://github.com/jpetazzo/pipework.git
    dest: /tmp/pipework
    depth: 1

- name: Copy to /usr/bin
  tags:
    - docker
    - pipework
  become: yes
  ignore_errors: yes
  shell: cp -f /tmp/pipework/pipework /usr/bin/pipework
