# Install Docker on Ubuntu 12.04
# https://docs.docker.com/engine/installation/ubuntulinux/

---
- name: Install dependence
  tags: docker
  become: True
  apt: name={{item}} state=latest update_cache=yes
  when: system_os is defined and system_os == 'ubuntu'
  with_items:
    - linux-image-generic-lts-trusty
    - linux-headers-generic-lts-trusty
    - xserver-xorg-lts-trusty
    - libgl1-mesa-glx-lts-trusty

- name: Install apt-key
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Update docker.list
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list mode=644

- name: Remove old lxc-docker
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  apt: name=lxc-docker state=absent purge=true

- name: Clean old docker file
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  file: path=/var/lib/docker state=absent

- name: Set user run docker without sudo
  become: yes
  ignore_errors: yes
  tags: docker
  when: system_os is defined and system_os == 'ubuntu'
  shell: {{ item }}
  with_items:
    - groupadd docker
    - "gpasswd -a {{user}} docker"
    - service docker restart

- name: Install new docker
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  apt: name=docker-engine state=latest update_cache=yes
