# Install Docker on Ubuntu 12.04
# https://docs.docker.com/engine/installation/ubuntulinux/

---
- name: Install dependence
  tags: docker
  become: True
  apt: name={{item}} state=latest update_cache=yes
  when: system_os is defined and system_os == 'ubuntu'
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Remove old docker
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  apt: name={{item}} state=absent purge=true
  with_items:
    - lxc-docker
    - docker
    - docker.io
    - docker-engine

- name: Clean old docker file
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  file: path=/var/lib/docker state=absent

- name: Install apt-key
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Update docker.list
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Set user run docker without sudo
  become: yes
  ignore_errors: yes
  tags: docker
  when: system_os is defined and system_os == 'ubuntu'
  shell: "{{ item }}"
  with_items:
    - groupadd docker
    - "gpasswd -a {{user}} docker"
    - service docker restart

- name: Install new docker
  tags: docker
  become: True
  when: system_os is defined and system_os == 'ubuntu'
  apt: name=docker-ce state=latest update_cache=yes
